### PR TITLE
napari plugin improvements

### PR DESCRIPTION
**Pull request by vineetbansal**
Fixes all bullets mentioned in issue #91 except:

- multiple widgets introduced when opening local h5ad files - in no case should the center align / pairwise align widget be added to the dock if it already exists there.

The above seems to be an issue with all plugins that I've tried (there's no way to detect which plugins are already "open" at a time). Its probably fine and we can leave it up to the user to close plugin widgets that were opened before data selection was made.

### CODE REVIEW

**Comment by anushka255** [comment]
I am trying to run `Center Alignment` using `napari` on this branch and the application crashes right after showing the message `Stacking slices around center slice` on the command line. The exact error message is 
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow should only be instantiated on the main thread!'
```
This issue is not encountered when running the test case for `center_align_widget`.

**Comment by vineetbansal** [comment]
And the same crash does not happen on the `main` branch?

**Comment by anushka255** [comment]
> And the same crash does not happen on the `main` branch?

No, it does not.

**Comment by vineetbansal** [comment]
@anushka255 - can you pull and try again?

**Review by anushka255 — APPROVED** [review]

**Pull request merged**
